Array

[[0 1 2]
 [3 2 4]]
 
List:

[{"age":25,"name":"john"},{"age":15,"name":"Pedro"}]

array

[1 2 3]+[1 2 3]=[2 4 6]

[1 2 3]*2=[2 4 6]

In [3]:
list_one=list(range(1,4))
list_two=list(range(1,4))
list_sum=[]
for index in range(3):
    list_one[index]**=2
    list_two[index]**=3
    list_sum.append(list_one[index]+list_two[index])
print(list_sum)

[2, 12, 36]


In [4]:
import numpy as np

In [5]:
array_one=np.arange(1,4)**2
array_two=np.arange(1,4)**3
array_sum=array_one+array_two
print(array_sum)

[ 2 12 36]


In [8]:
array_square=np.power(np.array([1,2,3]),2)
array_negative=np.negative(array_square)
print(array_square)
print(array_negative)

[1 4 9]
[-1 -4 -9]


In [10]:
array_exp=np.exp(np.array([0,1,2]))
print(array_exp)

[1.         2.71828183 7.3890561 ]


In [12]:
array_log=np.log(np.array([1,2,3]))
print(array_log)

[0.         0.69314718 1.09861229]


In [14]:
array_sin=np.sin(np.array([0,1,2]))
print(array_sin)

[0.         0.84147098 0.90929743]
