In [1]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
#return a view of the array original
ravelled_array=x.ravel()
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]


In [5]:
#return a copy of the new array
flattened_array=x.flatten()
print(flattened_array)

[0 1 2 3 4 5 6 7 8]


In [10]:
ravelled_array[2]=100
print(x)
#It is the original array

[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


In [11]:
flattened_array[4]=200
print(x)
print(flattened_array)
#It is a copy

[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]
[  0   1   2   3 200   5   6   7   8]


In [14]:
y=np.arange(9)
y.shape=[3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#transpouse
print(y.transpose())
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [17]:
print(np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [24]:
#one array of two matrix of 2 rows and 2 cols of zeros
np.zeros((2,2,2),dtype=int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [26]:
#identity matrix 3x3 
print(np.eye(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#matrix random rand
np.random.