In [50]:
import numpy as np
"""
We create a list of 0 to 17 or 18 items
and create three matrix of 2x3
(number_matrix,rows,cols)
or 
(rows,cols)
we create a array of three arrays with 
"""
x=np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [17]:
#access to the first matrix in the position 1,1
x[1,1,1]

10

In [35]:
#access to the second matrix the row 0 to 2 and col 0 to 2
x[1,:2,:3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
#acces to the two last matrix
x[1:3,...]

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [41]:
#access to all 0 rows and 0 cols of the three matrix 
x[:,0,0]

array([ 0,  6, 12])

In [42]:
#access to the second matrix and the 
x[1,:2,:3:2]

array([[ 6,  8],
       [ 9, 11]])

In [51]:
comparison_operation=x>5
print(comparison_operation)
print(x[comparison_operation])
print(x[x>5])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [52]:
print(x.max())
print(x.min())

17
0
