In [1]:
import numpy as np

In [3]:
x=np.array([0,3,5,5,5,2]).reshape(2,3)
x

array([[0, 3, 5],
       [5, 5, 2]])

In [4]:
y=np.array([3,4,3,-2,4,-2]).reshape(3,2)
y

array([[ 3,  4],
       [ 3, -2],
       [ 4, -2]])

In [8]:
product=x@y
product

array([[ 29, -16],
       [ 38,   6]])