MULTIDIMENTIONAL ARRAY

N dimentional array

[int16] [int16] [int32]

[int64] [float16] [uint16]

[uint64] [uint16] [float64]

In [2]:
import numpy as np

In [40]:
x=np.arange(3)
y=np.arange(3)
z=np.arange(3)
mult_array=np.array([x,y,z],dtype=np.int16)
print("Array: \n{} \n and shape: {} (rows,colums)".format(mult_array,mult_array.shape))

Array: 
[[0 1 2]
 [0 1 2]
 [0 1 2]] 
 and shape: (3, 3) (rows,colums)


In [17]:
w=np.linspace(0,1,10,False)
print(w)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [14]:
b=np.arange(0,10,3)
b

array([0, 3, 6, 9])

In [15]:
c=np.linspace(0,10,3)
c

array([ 0.,  5., 10.])

In [41]:
for i in range(3):
    for j in range(3):
        print(mult_array[i,j])

0
1
2
0
1
2
0
1
2
