In [1]:
import numpy as np

In [2]:
x=np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [3]:
y=np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [5]:
z=np.hstack((x,y))
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [ ]:
#Horizontal stack of two arrays 
#The number of rows of both arrays must be equal 
w=np.hstack((x,y))

In [6]:
x=np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [7]:
y=np.arange(8).reshape(4,2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
#Vertical stack of two arrays
#The number of the columns must be equal
w=np.vstack((x,y))
w

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In summary, horizontal stacking occurs along the second axis, second dimension(n,M), increasing the number of colums.

The second axix runs horizontally along the columns.

Vertical stacking occurs along the first axis, first dimension(N,m) increasing the number of rows

The first axis runs vertically downwards.


In [11]:
w=np.concatenate((x,y),axis=0)
w

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
x=np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [13]:
y=np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [15]:
w=np.concatenate((x,y),axis=1)
w

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [16]:
print(z==w)

[[ True  True  True  True]
 [ True  True  True  True]]


In [18]:
depth_stack=np.stack((z,w))
print(depth_stack)

[[[0 1 4 5]
  [2 3 6 7]]

 [[0 1 4 5]
  [2 3 6 7]]]


In [19]:
print(depth_stack.shape)

(2, 2, 4)


In [24]:
x=np.arange(4).reshape(2,1,2)
x

array([[[0, 1]],

       [[2, 3]]])

In [25]:
print(np.column_stack((z,w)))

[[0 1 4 5 0 1 4 5]
 [2 3 6 7 2 3 6 7]]


In [26]:
print(np.row_stack((z,w)))

[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
